name: alias_after_failed_update
runtime: python
